version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: laravel-metrics-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-laravel_metrics}
      POSTGRES_USER: ${POSTGRES_USER:-metrics_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-metrics_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=8
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-metrics_user} -d ${POSTGRES_DB:-laravel_metrics}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metrics-network

  #pgadmin is optional, but it's a good way to visualize the metrics
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: laravel-metrics-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin_password}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - metrics-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  metrics-network:
    driver: bridge
